### ISSUE TITLE
Yarn CLI Service is not Vite

### ISSUE THREAD

**Issue by sosensible** [chromaui/intro-storybook-vue-template#10]
It looks like this project is based on legacy build styles for Vue JS. I followed the guide to this page. ( https://storybook.js.org/tutorials/intro-to-storybook/vue/en/get-started/ ) I know, the first page. When running the suggested `yarn test:unit` it gave me this exception.

> yarn run v1.22.19
> $ vue-cli-service test:unit
> 'vue-cli-service' is not recognized as an internal or external command,
> operable program or batch file.
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Trying `yarn storybook` gave me this exception.

> yarn run v1.22.19
> $ start-storybook -p 6006
> 'start-storybook' is not recognized as an internal or external command,
> operable program or batch file.
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Did not try yarn serve. What will likely help is the install issue.

> yarn install v1.22.19
> [1/4] Resolving packages...
> [2/4] Fetching packages...
> error @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 || 16 || 17". Got "18.12.1"
> error Found incompatible module.
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> PS C:\dev2\learn\storybook\gs\taskbox> yarn test:unit
> yarn run v1.22.19
> $ vue-cli-service test:unit
> 'vue-cli-service' is not recognized as an internal or external command,
> operable program or batch file.
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

So, I could be wrong about Vite... though currently, we should be using Vite. My guess is the issue with v. 18 of Node also played into this. Looking at the node site it declared Node LTS is 18 so that module is out of current status, yes?

**Comment by jonniebigodes** [comment]
@sosensible, thanks once again for reaching out to us with your issue. We appreciate 🙏 ! I'm aware that the Vue CLI (in which this template is used) is currently in maintenance mode, and the recommendation is to use Vite. This is something that will be addressed in the upcoming year as the Vite integration with Storybook is improving greatly. In all fairness, I haven't committed to this because of time constraints due to the recently released Storybook beta version. If you're ok with it, I was thinking of looping you in once the pull request is up so that you can test it as well and we can polish it up where needed. Will that work for you?

Looking forward to hearing from you. Happy holidays
