### ISSUE TITLE
Following storybook guide, vue example layout broken

### ISSUE THREAD

**Issue by BuenGenio** [chromaui/intro-storybook-vue-template#5]
When I follow the setup steps on the [_intro to storibook_](https://storybook.js.org/tutorials/intro-to-storybook/vue/en/get-started/)

on `yarn serve` I got this weird layout:

![image](https://user-images.githubusercontent.com/629242/125152732-f17afd00-e14e-11eb-9b28-c6cc60ea5161.png)

Windows 10 EDGE (chromium version)/chrome

**Comment by jonniebigodes** [comment]
@BuenGenio that is happening because the [css](https://github.com/chromaui/intro-storybook-vue-template/blob/master/src/index.css)  required to the tutorial is being added into the [App.vue](https://github.com/chromaui/intro-storybook-vue-template/blob/master/src/App.vue#L20) component. I left it as a trade-off as people in the past forgot to add it and asked why the styling was not being applied.
